### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by U201412486** [ddarriba/prottest3#14]
Hi,
  my error is like this below.
  `Exception in thread "main" java.lang.OutOfMemoryError
        at java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:161)
        at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:155)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at es.uvigo.darwin.prottest.util.fileio.AlignmentReader.readAlignment(Unknown Source)
        at es.uvigo.darwin.prottest.global.options.ApplicationOptions.setAlignment(Unknown Source)
        at es.uvigo.darwin.prottest.global.options.ApplicationOptions.fillIn(Unknown Source)
        at es.uvigo.darwin.prottest.util.argumentparser.ProtTestArgumentParser.<init>(Unknown Source)
        at es.uvigo.darwin.prottest.util.argumentparser.AminoAcidArgumentParser.<init>(Unknown Source)
        at es.uvigo.darwin.prottest.util.factory.ProtTestFactory.createProtTestArgumentParser(Unknown Source)
        at es.uvigo.darwin.prottest.ProtTest.main(Unknown Source)`
  Can you give me some advice?
Thanks,
sun,

**Comment by ddarriba** [comment]
Hi Sun,

I would say that ProtTest is running out of memory. What alignment size causes that error?

**Comment by U201412486** [comment]
Sorry,It is my fault.I using wrong file as input.
  And I have solved my error.
